codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "60...90"

  status:
    project:
      default:
        target: 0%
    patch:
      default:
        target: 0%
    changes: no

comment:
  layout: "diff"
  behavior: new
  require_changes: yes
