/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package com.neuronrobotics.bowlerkernel.control.kinematics.limb

import com.google.common.collect.ImmutableList
import com.neuronrobotics.bowlerkernel.control.closedloop.JointAngleController
import com.neuronrobotics.bowlerkernel.control.kinematics.base.KinematicBase
import com.neuronrobotics.bowlerkernel.control.kinematics.limb.limbid.LimbId
import com.neuronrobotics.bowlerkernel.control.kinematics.limb.link.Link
import com.neuronrobotics.bowlerkernel.control.kinematics.motion.ForwardKinematicsSolver
import com.neuronrobotics.bowlerkernel.control.kinematics.motion.FrameTransformation
import com.neuronrobotics.bowlerkernel.control.kinematics.motion.InertialState
import com.neuronrobotics.bowlerkernel.control.kinematics.motion.InverseKinematicsSolver
import com.neuronrobotics.bowlerkernel.control.kinematics.motion.MotionConstraints
import com.neuronrobotics.bowlerkernel.control.kinematics.motion.plan.LimbMotionPlanFollower
import com.neuronrobotics.bowlerkernel.control.kinematics.motion.plan.LimbMotionPlanGenerator

/**
 * A limb of a robot, mounted to a [KinematicBase].
 */
interface Limb {

    /**
     * The unique (per-[KinematicBase]) id of this limb.
     */
    val id: LimbId

    /**
     * The links that form this limb.
     */
    val links: ImmutableList<Link>

    /**
     * The solver used for forward kinematics.
     */
    val forwardKinematicsSolver: ForwardKinematicsSolver

    /**
     * The solver used for inverse kinematics.
     */
    val inverseKinematicsSolver: InverseKinematicsSolver

    /**
     * The motion planner used to generate plans for the limb to follow.
     */
    val motionPlanGenerator: LimbMotionPlanGenerator

    /**
     * The motion plan follower used to follow plans generated by [motionPlanGenerator].
     */
    val motionPlanFollower: LimbMotionPlanFollower

    /**
     * The controllers for the joints.
     */
    val jointAngleControllers: ImmutableList<JointAngleController>

    /**
     * Sets a desired task space transform this limb should try to move to.
     *
     * @param taskSpaceTransform The desired task space transform.
     * @param motionConstraints The constraints on the motion to move from the current task
     * space transform to the desired [taskSpaceTransform].
     */
    fun setDesiredTaskSpaceTransform(
        taskSpaceTransform: FrameTransformation,
        motionConstraints: MotionConstraints
    )

    /**
     * The last set desired task space transform this limb should try to move to.
     */
    fun getDesiredTaskSpaceTransform(): FrameTransformation

    /**
     * The current task space transform.
     */
    fun getCurrentTaskSpaceTransform(): FrameTransformation

    /**
     * Sets a joint's desired angle.
     *
     * @param jointIndex The index of the joint.
     * @param jointAngle The new joint angle.
     * @param motionConstraints The constraints of the motion to move from the current joint
     * angle to the desired [jointAngle].
     */
    fun setDesiredJointAngle(
        jointIndex: Int,
        jointAngle: Number,
        motionConstraints: MotionConstraints
    )

    /**
     * The current joint angles.
     */
    fun getCurrentJointAngles(): ImmutableList<Double>

    /**
     * Compute whether the [taskSpaceTransform] is reachable by this limb.
     *
     * @param taskSpaceTransform The task space transform to test.
     * @return Whether the [taskSpaceTransform] is reachable.
     */
    fun isTaskSpaceTransformReachable(taskSpaceTransform: FrameTransformation): Boolean

    /**
     * Returns the current [InertialState] for this limb.
     *
     * @return The current [InertialState].
     */
    fun getInertialState(): InertialState

    /**
     * Returns the current [InertialState] for the link at [linkIndex] in [links].
     *
     * @param linkIndex The index of the [Link] in [links].
     * @return The current [InertialState].
     */
    fun getInertialState(linkIndex: Int): InertialState
}
